# Generated by Django 4.2.7 on 2023-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='address',
        ),
    ]
