# Generated by Django 4.2.7 on 2023-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
